name: Build and Deploy to Netlify
on:
  push:
    branches:
      - deploy
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build app
      - uses: actions/checkout@v4
        with:
          ref: deploy
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to Netlify
      - uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist/browser'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
